general:
  saveOnReload: true
  updateCheckerEnabled: true
shield:
  strength: 1.5
  radius: 5
  ignoreOps: false
  yStrength: 0.7
strings:
  prefix: "&8[&cRepulse&8]"
  activate: "&7You &aactivated &7the repulsing shield"
  deactivate: "&7You &cdeactivated &7the repulsing shield"
  noperm: "&cYou don't have permission to do that"

