name: Repulsor
version: 1.0.0
author: Max_Plays
main: me.MaxPlays.Repulsor.main.Repulsor
commands:
  repulsor:

permissions:
  repulsor.*:
    description: Everything
    children:
      repulsor.toggle: true