name: Repulse
version: 1.0.2
author: Max_Plays
main: me.MaxPlays.Repulse.main.Repulse
commands:
  repulse:

permissions:
  repulse.*:
    description: Everything
    children:
      repulse.toggle: true